// Auto-generated by `supabase gen types typescript --local > src/lib/types/database.ts`.
// Until first generation, use a permissive type that unblocks the client helpers.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Database = any
